openapi: 3.1.0
x-stoplight:
  id: oahoyklpxcnwl
info:
  title: API_3.1
  version: '1.0'
  contact:
    name: dfdsf1111
    url: dfsd22222
    email: ff444446666
  termsOfService: dfsdf55555
  license:
    name: dfsd
    url: dfsd
servers:
  - url: 'http://localhost:3000'
  - url: 'http://localhost:3000'
    description: ''
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: ha3faqo91r9a0
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: 1fw8y2oa689b1
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: elvbo78wlr73s
  '/users/{id}/test':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get
      tags: []
      responses: {}
      operationId: get-users-id-test
      x-stoplight:
        id: xjj9n6fqe1x7x
    post:
      summary: post
      tags: []
      responses: {}
      operationId: post-users-id-test
      x-stoplight:
        id: t179bvfcxvuoo
    put:
      summary: put
      tags: []
      responses: {}
      operationId: put-users-id-test
      x-stoplight:
        id: v2eykmrh7hrph
    patch:
      summary: patch
      tags: []
      responses: {}
      operationId: patch-users-id-test
      x-stoplight:
        id: diqfw5rghlfew
    delete:
      summary: delete
      tags: []
      responses: {}
      operationId: delete-users-id-test
      x-stoplight:
        id: ndajdc24ckm7z
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: lu0lpdwypu1d4
        firstName:
          type: string
          x-stoplight:
            id: tydk49t3f9pr9
        lastName:
          type: string
          x-stoplight:
            id: bcs6h010hptdr
        email:
          type: string
          format: email
          x-stoplight:
            id: d5vidpkg6m6z1
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: ktzrpsv7lwzi5
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: mu8nqm89h9n6f
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: isnoid5ida6p7
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: 7ceo1s8x7avgr
  securitySchemes:
    apiKey_1:
      name: apiKey
      type: apiKey
      in: query
security:
  - apiKey_1: []
